#!/usr/bin/env bash 

description=''
private=''
read -p 'Reponame: ' repo
read -p 'description: ' description
read -p 'private: ' private


if [ "$private" == "yes" ] || [ "$private" == "y" ]; then
    state=true
else
    state=false
fi


status_code=$(curl -s -w '%{http_code}' \
  -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer "\
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/user/repos \
  -d "{\"name\":\"$repo\",\"description\":\"$description\",\"private\":$state}"\
  -o /dev/null)

if  [ "$status_code" == "201" ]; then 
     echo "Success"
else 
     echo "Failed"
fi
